name: Build and Comment on PR

on:
  pull_request:

permissions:
  pull-requests: write  # Allows the workflow to post comments on PRs
  contents: read        # Grants read-only access to the repository contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Mock a build result
      - name: Mock Build Result
        id: build
        run: |
          echo "build_result=success" >> $GITHUB_OUTPUT

      # Step 2: Check for Existing Comments on the PR
      - name: Check for Existing Comments
        id: check-comments
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentTag = '<!-- build-status-comment -->'; // Tag to identify the comment
            const existingComments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });

            // Find the comment with the unique tag
            const duplicateComment = existingComments.data.find(comment =>
              comment.body.includes(commentTag)
            );

            if (duplicateComment) {
              core.setOutput('comment_id', duplicateComment.id);
              console.log(`Found comment with ID: ${duplicateComment.id}`);
            } else {
              core.setOutput('comment_id', '');
              console.log('No existing comment found.');
            }

      # Step 3: Add New Comment if Build Fails
      - name: Add New Comment
        if: steps.build.outputs.build_result == 'failure'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentTag = '<!-- build-status-comment -->'; // Tag to identify the comment
            const commentBody = `${commentTag}\n🚨 Build failed! Please check the logs.\n\nTarget branch: \`${context.payload.pull_request.base.ref}\`\nView the details [here](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`;

            const result = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: commentBody,
            });
            console.log(`Created new comment with ID: ${result.data.id}`);

      # Step 4: Delete Existing Comment (if any)
      - name: Delete Existing Comment
        if: steps.check-comments.outputs.comment_id != ''
        uses: actions/github-script@v6
        env:
          COMMENT_ID: ${{ steps.check-comments.outputs.comment_id }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(`Attempting to delete comment with ID: ${process.env.COMMENT_ID}`);
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: process.env.COMMENT_ID,
            });
            console.log(`Deleted comment with ID: ${process.env.COMMENT_ID}`);

      # Step 5: Remove Comment if Build Passes
      - name: Remove Comment if Build Passes
        if: steps.build.outputs.build_result == 'success' && steps.check-comments.outputs.comment_id != ''
        uses: actions/github-script@v6
        env:
          COMMENT_ID: ${{ steps.check-comments.outputs.comment_id }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(`Attempting to remove comment with ID: ${process.env.COMMENT_ID}`);
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: process.env.COMMENT_ID,
            });
            console.log(`Removed comment with ID: ${process.env.COMMENT_ID}`);
