name: Build and Comment on PR

on:
  pull_request:

permissions:
  pull-requests: write  # Allows the workflow to post comments on PRs
  contents: read        # Grants read-only access to the repository contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Mock a build result (replace with your actual build steps)
      - name: Mock Build Result
        id: build
        run: |
          echo "build_result=failure" >> $GITHUB_OUTPUT

      # Step 2: Check for existing comments on the PR
      - name: Check for Existing Comments
        id: check-comments
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentTag = '<!-- build-status-comment -->'; // Tag to identify the comment
            const existingComments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });

            // Find the comment with the unique tag
            const duplicateComment = existingComments.data.find(comment =>
              comment.body.includes(commentTag)
            );

            if (duplicateComment) {
              core.setOutput('comment_id', duplicateComment.id);
            } else {
              core.setOutput('comment_id', '');
            }

      # Step 3: Delete Existing Comment (if any)
      - name: Delete Existing Comment
        if: steps.check-comments.outputs.comment_id != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(`Deleting comment with ID: ${{ steps.check-comments.outputs.comment_id }}`);
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ steps.check-comments.outputs.comment_id }},
            });

      # Step 4: Post New Comment (if build fails)
      - name: Add New Comment
        if: steps.build.outputs.build_result == 'failure'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentTag = '<!-- build-status-comment -->'; // Tag to identify the comment
            const commentBody = `${commentTag}\n🚨 Build failed! Please check the logs.\n\nTarget branch: \`${context.payload.pull_request.base.ref}\`\nView the details [here](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: commentBody,
            });

      # Step 5: Remove Comment if Build Passes
      - name: Remove Comment if Build Passes
        if: steps.build.outputs.build_result == 'success' && steps.check-comments.outputs.comment_id != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(`Removing comment with ID: ${{ steps.check-comments.outputs.comment_id }}`);
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ steps.check-comments.outputs.comment_id }},
            });
