name: Fake PR Check

on:
  pull_request:

jobs:
  discover-workflow-id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Workflow ID
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Find the Workflow ID for this file
          WORKFLOW_FILE="fake-pr-check.yml"
          WORKFLOW_ID=$(gh workflow list --json id,name,path --jq \
            ".[] | select(.path == \".github/workflows/$WORKFLOW_FILE\") | .id")
          echo "Workflow ID: $WORKFLOW_ID"
          echo "workflow_id=$WORKFLOW_ID" >> $GITHUB_ENV
      
      - name: Simulate Processing with Delay
        run: |
          echo "Starting simulated delay..."
          sleep 30  # Delay for 30 seconds
          echo "Delay complete. Proceeding with workflow."

