name: Push Subtree to Shared SDK

on:
  push:
    branches:
      - '**' # Trigger on all branch pushes

jobs:
  push-subtree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Subtree to Shared SDK
        uses: karlludwigweise/git-subtree@v1
        with:
          action: add
          position: ${{ github.ref_name }} # Branch to push to
          repo: https://github.com/lironm16/ios # Target repository
          pat: ${{ secrets.SHARED_SDK_PAT }} # Deploy key stored as a secret
          prefix: 'IronSource/SharedLevelPlay/shared-sdk' # Subtree directory
