name: Push Subtree to Shared SDK

on:
  push:
    branches:
      - '**' # Trigger on all branch pushes

jobs:
  push-subtree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Subtree to Shared SDK
        uses: elanworld/subtree-sync-action@v1.0
        with:
          action: add
          branch: ${{ github.ref_name }} # Branch to push to
          repo: https://github.com/lironm16/shared-sdk # Target repository
          repo_token: ${{ secrets.SHARED_SDK_PAT }} # Deploy key stored as a secret
          path: 'IronSource/SharedLevelPlay/shared-sdk' # Subtree directory
