name: Push Subtree to Shared SDK

on:
  push:
    branches:
      - '**' # Trigger on all branch pushes

jobs:
  push-subtree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Push Subtree to Shared SDK
        uses: nxtlvlsoftware/git-subtree-action@master
        with:
          command: push
          prefix: IronSource/SharedLevelPlay/shared-sdk # Subtree path
          repository: git@github.com:lironm16/shared-sdk.git # Target repository
          branch: ${{ github.ref_name }} # Branch to push
          deploy_key: ${{ secrets.SHARED_SDK_DEPLOY_KEY }} # Deploy key for SSH auth
          tag: true # Automatically tag the push
