name: Sync Subtree with Tagging

on:
  push:
    branches:
      - '**'

jobs:
  sync-subtree:
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SHARED_SDK_DEPLOY_KEY }}"

      # Step 3: Configure Git
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      # Step 4: Pull and Merge Changes
      - name: Pull and Merge Remote Changes
        run: |
          SUBTREE_PATH="IronSource/SharedLevelPlay/shared-sdk"
          TARGET_REPO="git@github.com:lironm16/shared-sdk.git"
          TARGET_BRANCH="${{ github.ref_name }}"

          # Ensure the branch exists locally
          git checkout ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }}

          # Pull the latest changes from the remote branch and merge
          git pull $TARGET_REPO $TARGET_BRANCH || true

      # Step 5: Push Subtree to Shared SDK
      - name: Push Subtree to Shared SDK
        run: |
          SUBTREE_PATH="IronSource/SharedLevelPlay/shared-sdk"
          TARGET_REPO="git@github.com:lironm16/shared-sdk.git"
          TARGET_BRANCH="${{ github.ref_name }}"

          # Push the subtree after merging remote changes
          git subtree push --prefix=$SUBTREE_PATH $TARGET_REPO $TARGET_BRANCH

      # # Step 4: Push Subtree to Shared SDK
      # - name: Push Subtree to Shared SDK
      #   run: |
      #     SUBTREE_PATH="IronSource/SharedLevelPlay/shared-sdk"
      #     TARGET_REPO="git@github.com:lironm16/shared-sdk.git"
      #     TARGET_BRANCH="${{ github.ref_name }}"

      #     # Ensure the branch exists
      #     git checkout ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }}

      #     # Option 2: Force push subtree (overwrite remote)
      #     git subtree push --prefix=$SUBTREE_PATH $TARGET_REPO $TARGET_BRANCH

      # Step 5: Create and Push Tag
      - name: Create and Push Tag
        env:
          TAG_NAME: "sync-${{ github.ref_name }}-$(date +'%Y%m%d-%H%M%S')" # Dynamic tag name
        run: |
          git tag -a $TAG_NAME -m "Sync subtree from ${{ github.ref_name }}"
          git push origin $TAG_NAME
