name: Push Subtree to Shared SDK

on:
  push:
    branches:
      - '**' # Trigger on all branch pushes

jobs:
  push-subtree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Subtree to Shared SDK
        uses: xedi/action-subtree-sync@1.0.0
        with:
          subtree: 'lironm16/shared-sdk' # Target repository
          subtree_deploy_key: ${{ secrets.SHARED_SDK_DEPLOY_KEY }} # Deploy key stored as a secret
          split_prefix: 'IronSource/SharedLevelPlay/shared-sdk' # Subtree directory
          tag: true # Enable tagging
