name: Sync Subtree with Tagging

on:
  push:
    branches:
      - '**'

jobs:
  sync-subtree:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)" # Start ssh-agent
          echo "${{ secrets.SHARED_SDK_DEPLOY_KEY }}" | tr -d '\r' | ssh-add - # Add private key
          ssh-add -l # Verify the key is added


      # Debug SSH Connection
      - name: Test SSH Connection
        run: |
          ssh -T git@github.com

      # Debug SSH Key
      - name: Debug SSH Setup
        run: |
          echo "Checking SSH Agent:"
          eval "$(ssh-agent -s)"
          ssh-add -l
          echo "Testing SSH Connection to GitHub:"
          ssh -T git@github.com || true

          
      # Step 3: Configure Git
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      # Step 4: Push Subtree to Shared SDK
      - name: Push Subtree to Shared SDK
        run: |
          SUBTREE_PATH="IronSource/SharedLevelPlay/shared-sdk" # Path to the subtree directory
          TARGET_REPO="git@github.com:lironm16/shared-sdk.git" # Target repository
          TARGET_BRANCH="${{ github.ref_name }}" # Target branch matches source branch

          # Ensure the branch exists
          git checkout ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }}

          # Push subtree to the target repository using SSH
          git subtree push --prefix=$SUBTREE_PATH $TARGET_REPO $TARGET_BRANCH

      # Step 5: Create and Push Tag
      - name: Create and Push Tag
        env:
          TAG_NAME: "sync-${{ github.ref_name }}-$(date +'%Y%m%d-%H%M%S')" # Dynamic tag name
        run: |
          git tag -a $TAG_NAME -m "Sync subtree from ${{ github.ref_name }}"
          git push origin $TAG_NAME
