name: Re-run Specific Workflow for PRs

on:
  pull_request:
  repository_dispatch:
    types:
      - rerun-pr-check

jobs:
  rerun-checks:
    runs-on: ubuntu-latest

    steps:
      # - name: Install GitHub CLI
      #   run: sudo apt-get install gh -y

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Authentication for GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GitHub CLI is authenticated."

      - name: Fetch Open PRs Targeting the Branch
        id: fetch-prs
        run: |
          # Use the branch from the client payload
          TARGET_BRANCH="main"
          echo "Target Branch: $TARGET_BRANCH"

          # Fetch all open PRs targeting the specified branch
          PRS=$(gh pr list --state open --json number,baseRefName,headRefName,headRefOid --jq \
            ".[] | select(.baseRefName == \"$TARGET_BRANCH\") | {number: .number, branch: .headRefName, sha: .headRefOid}")
          echo "PR Data: $PRS"
          echo "pr_data=$PRS" >> $GITHUB_ENV

      - name: Re-run Latest Workflow for PRs
        run: |
          PRS_JSON=${{ env.pr_data }}
          WORKFLOW_FILE="fake-pr-check.yml"

          # Process each PR targeting the branch
          echo $PRS_JSON | jq -c '.[]' | while read pr; do
            PR_NUMBER=$(echo $pr | jq -r '.number')
            PR_BRANCH=$(echo $pr | jq -r '.branch')
            PR_SHA=$(echo $pr | jq -r '.sha')

            echo "Processing PR #$PR_NUMBER on branch $PR_BRANCH with SHA $PR_SHA..."

            # Fetch the latest run for the specific workflow filename
            RUN_ID=$(gh run list --json databaseId,workflowName,headBranch,headSha,createdAt,workflowPath --jq \
              ".[] | select(.workflowPath == \".github/workflows/$WORKFLOW_FILE\" and .headBranch == \"$PR_BRANCH\" and .headSha == \"$PR_SHA\") | sort_by(.createdAt) | last | .databaseId")

            # Ensure a matching run exists
            if [ -z "$RUN_ID" ]; then
              echo "No workflow runs found for PR #$PR_NUMBER with workflow file $WORKFLOW_FILE."
              continue
            fi

            # Re-run the latest workflow
            echo "Re-running workflow run with ID: $RUN_ID for PR #$PR_NUMBER..."
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/rerun
          done
