name: SharedLevelPlay PR Check

on:
  pull_request:

jobs:
  check-subtree:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout iOS Repository
      uses: actions/checkout@v3

    - name: Fetch shared-sdk Target Branch
      run: |
        # Use the target branch (base.ref) from the pull request
        TARGET_BRANCH=${{ github.event.pull_request.base.ref }}

        echo "Checking target branch: $TARGET_BRANCH"

        # Fetch the target branch from the shared-sdk repository
        git fetch https://github.com/lironm16/shared-sdk.git $TARGET_BRANCH

    - name: Compare Subtree with shared-sdk Target Branch
      run: |
        # Compare the contents of the shared-sdk subtree with the fetched target branch
        git diff --exit-code IronSource/SharedLevelPlay/shared-sdk FETCH_HEAD || (
          echo "The subtree (IronSource/SharedLevelPlay/shared-sdk) is not up-to-date with the shared-sdk $TARGET_BRANCH branch." && exit 1
        )
